export const QUERY_IDS = {
  MARKET_OVERVIEW: 6842786,
  SUPPLY_LEADERBOARD: 6842787,
  SUPPLY_OVER_TIME: 6842788,
  TRANSFER_VOLUME: 6842790,
  DAILY_ACTIVE_USERS: 6842791,
  CHAIN_DISTRIBUTION: 6842792,
  TOP_HOLDERS: 6842793,
  DEX_VOLUME: 6843561,
  DEX_PLATFORMS: 6843563,
  MARKET_SHARE: 6843568,
  LENDING: 6843569,
  DEX_POOLS: 6843570,
} as const;

// EUR query IDs — placeholder until Dune queries are created via MCP
export const EURO_QUERY_IDS = {
  MARKET_OVERVIEW: 6912622,
  SUPPLY_LEADERBOARD: 6912723,
  SUPPLY_OVER_TIME: 6912727,
  TRANSFER_VOLUME: 6912737,
  DAILY_ACTIVE_USERS: 6912742,
  CHAIN_DISTRIBUTION: 6912746,
  TOP_HOLDERS: 6912748,
  DEX_VOLUME: 6912756,
  DEX_PLATFORMS: 6912762,
  MARKET_SHARE: 6912795,
  LENDING: 6912785,
  DEX_POOLS: 6912781,
} as const;

export const CACHE_TTL_MS = 6 * 60 * 60 * 1000; // 6 hours

export const CHART_COLORS: Record<string, string> = {
  tGBP: "#00FF88",
  GBPm: "#5B7FFF",
  GBPe: "#FF6B35",
  GBPT: "#B44AFF",
  VGBP: "#00D4FF",
  eGBP: "#FFD700",
  EURC: "#2775CA",
  EURT: "#50AF95",
  EURS: "#2E86C1",
  EURA: "#FF6B6B",
  EURe: "#FF8C00",
  EURCV: "#8E44AD",
  EURI: "#1ABC9C",
  EUROe: "#3498DB",
  EURQ: "#E74C3C",
  EUROP: "#F39C12",
  EURR: "#27AE60",
  EURAU: "#9B59B6",
  PAR: "#2C3E50",
  sEUR: "#7D3C98",
  EURL: "#D4AC0D",
};

export const TOKEN_LOGOS: Record<string, string> = {
  tGBP: "/tokens/tGBP.png",
  GBPm: "/tokens/GBPm.png",
  GBPe: "/tokens/GBPe.png",
  GBPT: "/tokens/GBPT.png",
  VGBP: "/tokens/VGBP.png",
  eGBP: "/tokens/eGBP.png",
  USDT: "/tokens/USDT.png",
  USDC: "/tokens/USDC.png",
  EURC: "/tokens/EURC.png",
  EURT: "/tokens/EURT.png",
  EURS: "/tokens/EURS.png",
  EURA: "/tokens/EURA.png",
  EURe: "/tokens/EURe.png",
  EURCV: "/tokens/EURCV.png",
  EURI: "/tokens/EURI.png",
  AEUR: "/tokens/AEUR.svg",
  EURR: "/tokens/EURR.svg",
  EUROP: "/tokens/EUROP.png",
  EURm: "/tokens/EURm.png",
  VEUR: "/tokens/VEUR.png",
  PAR: "/tokens/PAR.png",
  EURAU: "/tokens/EURAU.png",
  EUROe: "/tokens/EUROe.png",
  IBEUR: "/tokens/IBEUR.png",
  sEUR: "/tokens/sEUR.png",
  eEUR: "/tokens/eEUR.png",
};

export const CHAIN_LOGOS: Record<string, string> = {
  ethereum: "/tokens/chain-ethereum.png",
  base: "/tokens/chain-base.png",
  polygon: "/tokens/chain-polygon.png",
  celo: "/tokens/chain-celo.png",
  gnosis: "/tokens/chain-gnosis.png",
  bnb: "/tokens/chain-bnb.png",
  arbitrum: "/tokens/chain-arbitrum.png",
  optimism: "/tokens/chain-optimism.png",
  avalanche_c: "/tokens/chain-avalanche_c.png",
  solana: "/tokens/chain-solana.png",
};

export const DEX_LOGOS: Record<string, string> = {
  uniswap: "/tokens/uniswap.png",
  curve: "/tokens/curve.png",
  mento: "/tokens/mento.png",
  balancer: "/tokens/balancer.png",
  sushiswap: "/tokens/sushiswap.png",
  pancakeswap: "/tokens/pancakeswap.png",
  aerodrome: "/tokens/aerodrome.png",
  velodrome: "/tokens/velodrome.png",
};

export const DEX_COLORS: Record<string, string> = {
  uniswap: "#FF007A",
  curve: "#0000FF",
  mento: "#35D07F",
  balancer: "#1E1E1E",
  sushiswap: "#FA52A0",
  pancakeswap: "#D1884F",
  aerodrome: "#0052FF",
  velodrome: "#FF0420",
};

export interface TokenMeta {
  issuer: string;
  color: string;
  regulation: string;
  backing: string;
  cex: string[];
  description: string;
}

export const TOKEN_META: Record<string, TokenMeta> = {
  tGBP: {
    issuer: "BCP Technologies",
    color: CHART_COLORS.tGBP,
    regulation: "FCA-registered (UK)",
    backing: "Cash + short-dated UK government bonds",
    cex: ["Kraken"],
    description: "First GBP stablecoin issued by an FCA-registered firm. Uses LayerZero OFT for cross-chain transfers.",
  },
  GBPm: {
    issuer: "Mento Protocol",
    color: CHART_COLORS.GBPm,
    regulation: "Mento governance",
    backing: "Algorithmic / Mento reserve",
    cex: [],
    description: "Formerly Celo British Pound (cGBP). Native to the Celo ecosystem with Mento stability mechanism.",
  },
  GBPe: {
    issuer: "Monerium",
    color: CHART_COLORS.GBPe,
    regulation: "Central Bank of Iceland (MiCAR-compliant)",
    backing: "E-money — 1:1 GBP reserves",
    cex: ["LBank"],
    description: "Authorised e-money token. Integrated with Gnosis Pay for real-world card spending.",
  },
  GBPT: {
    issuer: "Blackfridge SC (Poundtoken)",
    color: CHART_COLORS.GBPT,
    regulation: "Isle of Man FSA",
    backing: "100% fiat reserves in segregated UK bank accounts",
    cex: ["CEX.IO", "Gate.io (hist.)"],
    description: "Monthly KPMG proof-of-reserve attestations. Integrated with Fireblocks (1,300+ institutions).",
  },
  VGBP: {
    issuer: "VNX",
    color: CHART_COLORS.VGBP,
    regulation: "Liechtenstein Blockchain Act",
    backing: "1:1 GBP reserves (Swiss/Liechtenstein banks)",
    cex: ["Coinbase"],
    description: "Multi-chain deployment including Solana. Active Aerodrome DEX liquidity on Base.",
  },
  eGBP: {
    issuer: "Aryze",
    color: CHART_COLORS.eGBP,
    regulation: "Danish FSA (VASP)",
    backing: "Short-term government bonds",
    cex: ["Mercado Bitcoin"],
    description: "Part of Aryze's multi-currency suite (eUSD, eEUR, eGBP). Cross-currency conversion built in.",
  },
  EURC: {
    issuer: "Circle",
    color: CHART_COLORS.EURC,
    regulation: "MiCA-compliant (France AMF)",
    backing: "1:1 EUR reserves held by regulated EU financial institutions",
    cex: ["Coinbase", "Binance", "Kraken", "Bitstamp"],
    description: "Circle's euro-denominated stablecoin. Native CCTP cross-chain transfers. Largest EUR stablecoin by market cap.",
  },
  EURT: {
    issuer: "Tether",
    color: CHART_COLORS.EURT,
    regulation: "Limited (no MiCA licence)",
    backing: "Tether reserves (cash equivalents, commercial paper)",
    cex: ["Bitfinex", "Kraken"],
    description: "Tether's euro stablecoin. Discontinued Nov 2025 due to MiCA requirements. Historical data only.",
  },
  EURS: {
    issuer: "Stasis",
    color: CHART_COLORS.EURS,
    regulation: "Malta (MFSA)",
    backing: "1:1 EUR reserves in EU bank accounts",
    cex: ["Bitfinex", "HitBTC"],
    description: "One of the earliest EUR stablecoins. Fiat-backed with regular audits by BDO.",
  },
  EURA: {
    issuer: "Angle Protocol",
    color: CHART_COLORS.EURA,
    regulation: "Decentralised governance",
    backing: "Crypto-collateralised (overcollateralised vaults)",
    cex: [],
    description: "Formerly agEUR. Decentralised EUR stablecoin backed by crypto collateral. Active on Ethereum, Polygon, and other chains.",
  },
  EURe: {
    issuer: "Monerium",
    color: CHART_COLORS.EURe,
    regulation: "Central Bank of Iceland (MiCAR-compliant)",
    backing: "E-money — 1:1 EUR reserves",
    cex: [],
    description: "Authorised e-money EUR token. Integrated with Gnosis Pay for real-world card spending.",
  },
  EURCV: {
    issuer: "SG-Forge (Société Générale)",
    color: CHART_COLORS.EURCV,
    regulation: "AMF France (MiCA-compliant)",
    backing: "Fiat reserves backed by Société Générale",
    cex: ["Bitstamp"],
    description: "Institutional-grade EUR stablecoin from Société Générale's digital asset subsidiary.",
  },
  EURI: {
    issuer: "Banking Circle",
    color: CHART_COLORS.EURI,
    regulation: "Luxembourg (CRR credit institution)",
    backing: "1:1 EUR reserves in Banking Circle accounts",
    cex: [],
    description: "MiCA-compliant EUR e-money token from Banking Circle, a licensed credit institution.",
  },
  AEUR: {
    issuer: "Anchored Coins",
    color: "#2ECC71",
    regulation: "BaFin (Germany)",
    backing: "Fiat reserves in European banks",
    cex: [],
    description: "German-regulated EUR stablecoin. Fiat-backed with reserves in European banking institutions.",
  },
  EURR: {
    issuer: "StablR",
    color: CHART_COLORS.EURR,
    regulation: "Malta (MiCA-compliant)",
    backing: "1:1 EUR reserves",
    cex: [],
    description: "MiCA-compliant EUR stablecoin issued by StablR. Available on Ethereum and Solana.",
  },
  EUROP: {
    issuer: "Schuman Financial",
    color: CHART_COLORS.EUROP,
    regulation: "France AMF (MiCA-compliant)",
    backing: "1:1 EUR reserves",
    cex: [],
    description: "MiCA-compliant EUR stablecoin from Schuman Financial. Multi-chain deployment.",
  },
  EURm: {
    issuer: "Mento Protocol",
    color: "#35D07F",
    regulation: "Mento governance",
    backing: "Algorithmic / Mento reserve",
    cex: [],
    description: "Mento Euro stablecoin. Part of the Celo ecosystem with Mento stability mechanism.",
  },
  VEUR: {
    issuer: "VNX",
    color: "#00D4FF",
    regulation: "Liechtenstein Blockchain Act",
    backing: "1:1 EUR reserves",
    cex: [],
    description: "VNX Euro stablecoin. Multi-chain deployment on Tezos, Base, and Ethereum.",
  },
  EURAU: {
    issuer: "AllUnity",
    color: CHART_COLORS.EURAU,
    regulation: "MiCA-compliant",
    backing: "Fiat reserves",
    cex: [],
    description: "AllUnity EUR stablecoin. Available on Ethereum, Optimism, Polygon, and Base.",
  },
};
